import {
  calculateSampleSize,
  calculateMDE,
  calculateMDEFromSampleSize,
} from "./statistics.js";

let passedTests = 0;
let failedTests = 0;
let failedTestNames = [];

function areClose(a, b, tolerance = 0.01) {
  if (a === 0 && b === 0) return true;
  const relError = Math.abs((a - b) / Math.max(Math.abs(a), Math.abs(b)));
  return relError <= tolerance;
}

function createDebugPanel() {
  const debugPanel = document.createElement("div");
  debugPanel.id = "debug-panel";
  debugPanel.style.cssText =
    "position: fixed; bottom: 10px; right: 10px; background: rgba(30,30,30,0.9); color: white; padding: 10px; max-width: min(500px, calc(100vw - 20px)); width: 100%; max-height: 500px; overflow-y: auto; font-family: monospace; font-size: 12px; z-index: 9999; border-radius: 6px; box-shadow: 0 4px 8px rgba(0,0,0,0.3); transition: all 0.3s ease;";
  const header = document.createElement("div");
  header.style.cssText =
    "display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px; padding-bottom: 8px; border-bottom: 1px solid rgba(255,255,255,0.2);";

  const title = document.createElement("h3");
  title.textContent = "🧪 Test results";
  title.style.cssText = "margin: 0; font-size: 14px; color: #fff;";

  const closeButton = document.createElement("button");
  closeButton.textContent = "×";
  closeButton.style.cssText =
    "background: none; border: none; color: #ccc; font-size: 18px; cursor: pointer; padding: 0 5px;";
  closeButton.onclick = function () {
    debugPanel.style.opacity = "0";
    setTimeout(() => {
      debugPanel.style.display = "none";
    }, 300);
  };

  header.appendChild(title);
  header.appendChild(closeButton);
  debugPanel.appendChild(header);

  const content = document.createElement("div");
  content.id = "debug-content";
  content.style.cssText = "overflow-y: auto; max-height: 320px;";
  debugPanel.appendChild(content);

  const controls = document.createElement("div");
  controls.style.cssText =
    "display: flex; justify-content: space-between; margin-top: 8px; padding-top: 8px; border-top: 1px solid rgba(255,255,255,0.2);";

  const clearButton = document.createElement("button");
  clearButton.textContent = "Clear";
  clearButton.style.cssText =
    "background: #555; border: none; color: white; padding: 4px 8px; border-radius: 3px; cursor: pointer; font-size: 11px;";
  clearButton.onclick = function () {
    document.getElementById("debug-content").innerHTML = "";
    passedTests = 0;
    failedTests = 0;
  };

  const runTestsButton = document.createElement("button");
  runTestsButton.textContent = "Run Tests Again";
  runTestsButton.style.cssText =
    "background: #4a90e2; border: none; color: white; padding: 4px 8px; border-radius: 3px; cursor: pointer; font-size: 11px;";
  runTestsButton.onclick = function () {
    document.getElementById("debug-content").innerHTML = "";
    passedTests = 0;
    failedTests = 0;
    runAllTests();
  };

  controls.appendChild(clearButton);
  controls.appendChild(runTestsButton);
  debugPanel.appendChild(controls);

  return debugPanel;
}

function debugLog(message, type = "info") {
  const content = document.getElementById("debug-content");
  if (!content) return;

  const p = document.createElement("div");
  p.style.cssText =
    "margin: 4px 0; padding: 3px 0; border-bottom: 1px solid rgba(255,255,255,0.1);";

  switch (type) {
    case "pass":
      p.style.color = "#4caf50";
      message = `✅ ${message}`;
      break;
    case "fail":
      p.style.color = "#f44336";
      message = `❌ ${message}`;
      break;
    case "header":
      p.style.fontWeight = "bold";
      p.style.color = "#ffeb3b";
      p.style.paddingTop = "6px";
      break;
    case "summary":
      p.style.fontWeight = "bold";
      p.style.marginTop = "8px";
      break;
    default:
      p.style.color = "#ffffff";
  }

  p.textContent = message;
  content.appendChild(p);
  console.log(message);

  requestAnimationFrame(() => {
    content.scrollTop = content.scrollHeight;
  });
}

const regressionTestCases = [
  // Start of tests generated from TrialSize::TwoSampleProportion.NIS (margin=0) on 2025-06-21
  {
    name: "Small superiority",
    baseline: 0.1,
    relativeEffectSize: 0.02,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "one-sided",
    correctionMethod: "none",
    expectedSampleSize: 280682,
  },
  {
    name: "Basic superiority",
    baseline: 0.1,
    relativeEffectSize: 0.2,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "one-sided",
    correctionMethod: "none",
    expectedSampleSize: 3023,
  },
  {
    name: "High power superiority",
    baseline: 0.05,
    relativeEffectSize: 0.4,
    alpha: 0.05,
    power: 0.9,
    variantCount: 2,
    buffer: 0,
    testType: "one-sided",
    correctionMethod: "none",
    expectedSampleSize: 2411,
  },
  {
    name: "Small effect superiority",
    baseline: 0.2,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "one-sided",
    correctionMethod: "none",
    expectedSampleSize: 5125,
  },
  {
    name: "Large effect superiority",
    baseline: 0.15,
    relativeEffectSize: 0.5,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "one-sided",
    correctionMethod: "none",
    expectedSampleSize: 332,
  },
  {
    name: "Strict alpha superiority",
    baseline: 0.1,
    relativeEffectSize: 0.3,
    alpha: 0.01,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "one-sided",
    correctionMethod: "none",
    expectedSampleSize: 2265,
  },
  {
    name: "Conservative superiority",
    baseline: 0.08,
    relativeEffectSize: 0.25,
    alpha: 0.025,
    power: 0.95,
    variantCount: 2,
    buffer: 0,
    testType: "one-sided",
    correctionMethod: "none",
    expectedSampleSize: 5315,
  },
  {
    name: "E-commerce superiority",
    baseline: 0.03,
    relativeEffectSize: 0.33,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "one-sided",
    correctionMethod: "none",
    expectedSampleSize: 4252,
  },
  {
    name: "Email superiority",
    baseline: 0.25,
    relativeEffectSize: 0.2,
    alpha: 0.05,
    power: 0.85,
    variantCount: 2,
    buffer: 0,
    testType: "one-sided",
    correctionMethod: "none",
    expectedSampleSize: 1143,
  },
  {
    name: "Sign-up superiority",
    baseline: 0.12,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.9,
    variantCount: 2,
    buffer: 0,
    testType: "one-sided",
    correctionMethod: "none",
    expectedSampleSize: 5935,
  },
  {
    name: "Purchase superiority",
    baseline: 0.45,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "one-sided",
    correctionMethod: "none",
    expectedSampleSize: 1519,
  },
  // End of tests generated from TrialSize::TwoSampleProportion.NIS (margin=0) on 2025-06-21
  {
    name: "E-commerce (one-sided)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "one-sided",
    expectedSampleSize: 24601,
  },
  {
    name: "E-commerce (two-sided)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    testType: "two-sided",
    expectedSampleSize: 31231,
  },
  {
    name: "High CR (one-sided)",
    baseline: 0.5,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    testType: "one-sided",
    expectedSampleSize: 1231,
  },
  {
    name: "Low CR (one-sided)",
    baseline: 0.01,
    relativeEffectSize: 0.2,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    testType: "one-sided",
    expectedSampleSize: 33627,
  },
  {
    name: "Small effect (one-sided)",
    baseline: 0.05,
    relativeEffectSize: 0.05,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    testType: "one-sided",
    expectedSampleSize: 96195,
  },
  {
    name: "Three variants (one-sided; Šidák)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    testType: "one-sided",
    expectedSampleSize: 31110,
    correctionMethod: "sidak",
  },
  {
    name: "High power (one-sided)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.01,
    power: 0.9,
    variantCount: 2,
    testType: "one-sided",
    expectedSampleSize: 51795,
  },
  {
    name: "Very low CR (one-sided)",
    baseline: 0.001,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    testType: "one-sided",
    expectedSampleSize: 590140,
  },
  {
    name: "Ultra high confidence (one-sided)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.001,
    power: 0.8,
    variantCount: 2,
    testType: "one-sided",
    expectedSampleSize: 61514,
  },
  {
    name: "Many variants (one-sided; Šidák)",
    baseline: 0.1,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    testType: "one-sided",
    expectedSampleSize: 8063,
    correctionMethod: "sidak",
  },
  {
    name: "Typical e-commerce",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 31231,
  },
  {
    name: "High conversion rate",
    baseline: 0.5,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 1562,
  },
  {
    name: "Low conversion rate",
    baseline: 0.01,
    relativeEffectSize: 0.2,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 42691,
  },
  {
    name: "Small effect size",
    baseline: 0.05,
    relativeEffectSize: 0.05,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 122121,
  },
  {
    name: "Three variants (Šidák)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    expectedSampleSize: 37700,
    correctionMethod: "sidak",
  },
  {
    name: "High power",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.01,
    power: 0.9,
    variantCount: 2,
    expectedSampleSize: 59206,
  },
  {
    name: "Edge case: very low CR",
    baseline: 0.001,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 749194,
  },
  {
    name: "Very high CR",
    baseline: 0.75,
    relativeEffectSize: 0.08,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 745,
  },
  {
    name: "Modest CR",
    baseline: 0.25,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 2190,
  },
  {
    name: "Mobile app CR",
    baseline: 0.035,
    relativeEffectSize: 0.12,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 31787,
  },
  {
    name: "Super low CR",
    baseline: 0.0025,
    relativeEffectSize: 0.18,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 210662,
  },
  {
    name: "Four variants (Šidák)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    expectedSampleSize: 41497,
    correctionMethod: "sidak",
  },
  {
    name: "Five variants (Šidák)",
    baseline: 0.1,
    relativeEffectSize: 0.12,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    expectedSampleSize: 14612,
    correctionMethod: "sidak",
  },
  {
    name: "Very high power",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.01,
    power: 0.95,
    variantCount: 2,
    expectedSampleSize: 70883,
  },
  {
    name: "Conservative test",
    baseline: 0.15,
    relativeEffectSize: 0.08,
    alpha: 0.001,
    power: 0.9,
    variantCount: 2,
    expectedSampleSize: 38216,
  },
  {
    name: "Tiny effect",
    baseline: 0.1,
    relativeEffectSize: 0.03,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 159063,
  },
  {
    name: "Ultra low CR, large effect",
    baseline: 0.0005,
    relativeEffectSize: 0.25,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 564798,
  },
  {
    name: "Ultra high confidence",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.0001,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 89106,
  },
  {
    name: "Very low confidence",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.8,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 4771,
  },
  {
    name: "Microscopic CR",
    baseline: 0.0001,
    relativeEffectSize: 0.2,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 4316406,
  },
  {
    name: "Near perfect CR",
    baseline: 0.9999,
    relativeEffectSize: 0.0001,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 79282,
  },
  {
    name: "Near certain detection",
    baseline: 0.1,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.9999,
    variantCount: 2,
    expectedSampleSize: 60600,
  },
  {
    name: "Very low power",
    baseline: 0.1,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.1,
    variantCount: 2,
    expectedSampleSize: 865,
  },
  {
    name: "Minuscule effect",
    baseline: 0.5,
    relativeEffectSize: 0.001,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 15697752,
  },
  {
    name: "Many variants, low alpha (Šidák)",
    baseline: 0.01,
    relativeEffectSize: 0.1,
    alpha: 0.001,
    power: 0.99,
    variantCount: 10,
    expectedSampleSize: 796477,
    correctionMethod: "sidak",
  },
  {
    name: "Low CR, many variants (Šidák)",
    baseline: 0.001,
    relativeEffectSize: 0.05,
    alpha: 0.05,
    power: 0.8,
    variantCount: 8,
    expectedSampleSize: 10175229,
    correctionMethod: "sidak",
  },
  {
    name: "Realistic extreme",
    baseline: 0.0005,
    relativeEffectSize: 0.5,
    alpha: 0.1,
    power: 0.7,
    variantCount: 2,
    expectedSampleSize: 94053,
  },
  {
    name: "Buffer test (10%)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 10,
    testType: "two-sided",
    expectedSampleSize: 34354, // 31231 * 1.1
  },
  {
    name: "Buffer test (25%)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 25,
    testType: "two-sided",
    expectedSampleSize: 39039, // 31231 * 1.25
  },
  {
    name: "Buffer test (100%)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 100,
    testType: "two-sided",
    expectedSampleSize: 62462, // 31231 * 2
  },
  {
    name: "E-commerce (3 variants, none)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 31231,
  },
  {
    name: "E-commerce (3 variants, bonferroni)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 37821,
  },
  {
    name: "E-commerce (3 variants, sidak)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 37700,
  },
  {
    name: "E-commerce (5 variants, none)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 31231,
  },
  {
    name: "E-commerce (5 variants, bonferroni)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 44371,
  },
  {
    name: "E-commerce (5 variants, sidak)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 44190,
  },
  {
    name: "High traffic site (3 variants, none)",
    baseline: 0.1,
    relativeEffectSize: 0.08,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 22853,
  },
  {
    name: "High traffic site (3 variants, bonferroni)",
    baseline: 0.1,
    relativeEffectSize: 0.08,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 27674,
  },
  {
    name: "High traffic site (3 variants, sidak)",
    baseline: 0.1,
    relativeEffectSize: 0.08,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 27586,
  },
  {
    name: "High traffic site (5 variants, none)",
    baseline: 0.1,
    relativeEffectSize: 0.08,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 22853,
  },
  {
    name: "High traffic site (5 variants, bonferroni)",
    baseline: 0.1,
    relativeEffectSize: 0.08,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 32467,
  },
  {
    name: "High traffic site (5 variants, sidak)",
    baseline: 0.1,
    relativeEffectSize: 0.08,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 32335,
  },
  {
    name: "Low CR site (3 variants, none)",
    baseline: 0.01,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 74191,
  },
  {
    name: "Low CR site (3 variants, bonferroni)",
    baseline: 0.01,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 89845,
  },
  {
    name: "Low CR site (3 variants, sidak)",
    baseline: 0.01,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 89558,
  },
  {
    name: "Low CR site (5 variants, none)",
    baseline: 0.01,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 74191,
  },
  {
    name: "Low CR site (5 variants, bonferroni)",
    baseline: 0.01,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 105404,
  },
  {
    name: "Low CR site (5 variants, sidak)",
    baseline: 0.01,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 104976,
  },
  {
    name: "E-commerce checkout",
    baseline: 0.03,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 10,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 26610,
  },
  {
    name: "Email click-through",
    baseline: 0.12,
    relativeEffectSize: 0.08,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "one-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 14652,
  },
  {
    name: "SaaS sign-up",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.9,
    variantCount: 2,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 41810,
  },
  // Tests generated by TrialSize::TwoSampleProportion.Equality.
  {
    name: "Basic two-sided",
    baseline: 0.1,
    relativeEffectSize: 0.2,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 3838,
  },
  {
    name: "High power equality",
    baseline: 0.05,
    relativeEffectSize: 0.4,
    alpha: 0.05,
    power: 0.9,
    variantCount: 2,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 2958,
  },
  {
    name: "Small effect",
    baseline: 0.2,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 6507,
  },
  {
    name: "Large effect",
    baseline: 0.15,
    relativeEffectSize: 0.5,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 421,
  },
  {
    name: "Strict alpha",
    baseline: 0.1,
    relativeEffectSize: 0.3,
    alpha: 0.01,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 2636,
  },
  {
    name: "Conservative test",
    baseline: 0.08,
    relativeEffectSize: 0.25,
    alpha: 0.025,
    power: 0.95,
    variantCount: 2,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 6177,
  },
  {
    name: "E-commerce conversion",
    baseline: 0.03,
    relativeEffectSize: 0.33,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 5398,
  },
  {
    name: "Email click rate",
    baseline: 0.25,
    relativeEffectSize: 0.2,
    alpha: 0.05,
    power: 0.85,
    variantCount: 2,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 1428,
  },
  {
    name: "Sign-up rate",
    baseline: 0.12,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.9,
    variantCount: 2,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 7282,
  },
  {
    name: "Purchase completion",
    baseline: 0.45,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 1928,
  },
  // End of tests generated by TrialSize::TwoSampleProportion.Equality.
  {
    name: "High variant count (20, bonferroni)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 20,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 58961,
  },
  {
    name: "High variant count (20, sidak)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 20,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 58736,
  },

  // Extreme alpha values
  {
    name: "Alpha=0.0001",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.0001,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 89106,
  },
  {
    name: "Alpha=0.0001 w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.0001,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 101733,
  },
  {
    name: "Alpha=0.0001 w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.0001,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 101733,
  },
  {
    name: "Alpha=0.001",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.001,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 67941,
  },
  {
    name: "Alpha=0.001 w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.001,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 80714,
  },
  {
    name: "Alpha=0.001 w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.001,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 80711,
  },
  {
    name: "Alpha=0.1",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.1,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 24601,
  },
  {
    name: "Alpha=0.1 w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.1,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 37821,
  },
  {
    name: "Alpha=0.1 w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.1,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 37451,
  },
  {
    name: "Alpha=0.2",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.2,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 17937,
  },
  {
    name: "Alpha=0.2 w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.2,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 31231,
  },
  {
    name: "Alpha=0.2 w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.2,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 30451,
  },

  // Test type interaction
  {
    name: "one-sided",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 0,
    testType: "one-sided",
    correctionMethod: "none",
    expectedSampleSize: 24601,
  },
  {
    name: "one-sided w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 0,
    testType: "one-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 35091,
  },
  {
    name: "one-sided w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 0,
    testType: "one-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 34929,
  },
  {
    name: "two-sided",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 31231,
  },
  {
    name: "two-sided w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 41657,
  },
  {
    name: "two-sided w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 41497,
  },

  // Extreme conversion rates
  {
    name: "CR=0.0001",
    baseline: 0.0001,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 16480913,
  },
  {
    name: "CR=0.0001 w/ Bonferroni",
    baseline: 0.0001,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 19958477,
  },
  {
    name: "CR=0.0001 w/ Šidák",
    baseline: 0.0001,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 19894748,
  },
  {
    name: "CR=0.001",
    baseline: 0.001,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 1646531,
  },
  {
    name: "CR=0.001 w/ Bonferroni",
    baseline: 0.001,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 1993958,
  },
  {
    name: "CR=0.001 w/ Šidák",
    baseline: 0.001,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 1987591,
  },
  {
    name: "CR=0.999",
    baseline: 0.999,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 1,
  },
  {
    name: "CR=0.999 w/ Bonferroni",
    baseline: 0.999,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 1,
  },
  {
    name: "CR=0.999 w/ Šidák",
    baseline: 0.999,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 1,
  },
  {
    name: "CR=0.9999",
    baseline: 0.9999,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 1,
  },
  {
    name: "CR=0.9999 w/ Bonferroni",
    baseline: 0.9999,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 1,
  },
  {
    name: "CR=0.9999 w/ Šidák",
    baseline: 0.9999,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 1,
  },

  // Extreme MDE values
  {
    name: "MDE=0.001",
    baseline: 0.05,
    relativeEffectSize: 0.001,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 298398702,
  },
  {
    name: "MDE=0.001 w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.001,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 361362478,
  },
  {
    name: "MDE=0.001 w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.001,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 360208624,
  },
  {
    name: "MDE=0.01",
    baseline: 0.05,
    relativeEffectSize: 0.01,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 2996695,
  },
  {
    name: "MDE=0.01 w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.01,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 3629014,
  },
  {
    name: "MDE=0.01 w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.01,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 3617426,
  },
  {
    name: "MDE=0.5",
    baseline: 0.05,
    relativeEffectSize: 0.5,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 1468,
  },
  {
    name: "MDE=0.5 w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.5,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 1778,
  },
  {
    name: "MDE=0.5 w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.5,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 1772,
  },
  {
    name: "MDE=0.8",
    baseline: 0.05,
    relativeEffectSize: 0.8,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 635,
  },
  {
    name: "MDE=0.8 w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.8,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 769,
  },
  {
    name: "MDE=0.8 w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.8,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 767,
  },

  // Buffer interaction
  {
    name: "Buffer=10%",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 10,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 34354,
  },
  {
    name: "Buffer=10% w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 10,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 45823,
  },
  {
    name: "Buffer=10% w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 10,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 45646,
  },
  {
    name: "Buffer=50%",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 50,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 46847,
  },
  {
    name: "Buffer=50% w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 50,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 62485,
  },
  {
    name: "Buffer=50% w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 50,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 62245,
  },
  {
    name: "Buffer=100%",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 100,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 62462,
  },
  {
    name: "Buffer=100% w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 100,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 83314,
  },
  {
    name: "Buffer=100% w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 100,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 82993,
  },
  // Start of tests generated from epiR::epi.ssninfb.
  {
    name: "Basic non-inferiority",
    baseline: 0.1,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 11129,
  },
  {
    name: "Conservative non-inferiority",
    baseline: 0.05,
    relativeEffectSize: 0.05,
    alpha: 0.025,
    power: 0.9,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 159713,
  },
  {
    name: "High baseline, tight margin",
    baseline: 0.3,
    relativeEffectSize: 0.05,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 11541,
  },
  {
    name: "Low baseline, loose margin",
    baseline: 0.02,
    relativeEffectSize: 0.2,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 15148,
  },
  {
    name: "Medium baseline, medium margin",
    baseline: 0.15,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.85,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 8148,
  },
  {
    name: "High power, tight margin",
    baseline: 0.2,
    relativeEffectSize: 0.05,
    alpha: 0.025,
    power: 0.95,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 41584,
  },
  {
    name: "E-commerce conversion",
    baseline: 0.03,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 39981,
  },
  {
    name: "Email open rate",
    baseline: 0.25,
    relativeEffectSize: 0.04,
    alpha: 0.05,
    power: 0.9,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 32115,
  },
  {
    name: "Click-through rate",
    baseline: 0.08,
    relativeEffectSize: 0.125,
    alpha: 0.025,
    power: 0.85,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 13217,
  },
  {
    name: "Sign-up conversion",
    baseline: 0.18,
    relativeEffectSize: 0.06,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 15648,
  },
  // End of tests generated from epiR::epi.ssninfb.
  // Start of tests generated from TrialSize::TwoSampleProportion.NIS on 202506-21
  {
    name: "Basic non-inferiority",
    baseline: 0.1,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 11129,
  },
  {
    name: "Conservative non-inferiority",
    baseline: 0.05,
    relativeEffectSize: 0.05,
    alpha: 0.025,
    power: 0.9,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 159713,
  },
  {
    name: "Tight margin non-inf",
    baseline: 0.2,
    relativeEffectSize: 0.02,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 123651,
  },
  {
    name: "Loose margin non-inf",
    baseline: 0.15,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.85,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 3621,
  },
  {
    name: "High power non-inf",
    baseline: 0.3,
    relativeEffectSize: 0.05,
    alpha: 0.05,
    power: 0.95,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 20201,
  },
  {
    name: "Strict alpha non-inf",
    baseline: 0.12,
    relativeEffectSize: 0.08,
    alpha: 0.01,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 22999,
  },
  {
    name: "E-commerce non-inf",
    baseline: 0.03,
    relativeEffectSize: 0.2,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 9995,
  },
  {
    name: "Email non-inf",
    baseline: 0.25,
    relativeEffectSize: 0.04,
    alpha: 0.05,
    power: 0.9,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 32114,
  },
  {
    name: "Click rate non-inf",
    baseline: 0.08,
    relativeEffectSize: 0.1,
    alpha: 0.025,
    power: 0.85,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 20650,
  },
  {
    name: "Purchase non-inf",
    baseline: 0.45,
    relativeEffectSize: 0.03,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 16792,
  },
  // End of tests generated from TrialSize::TwoSampleProportion.NIS on 202506-21
  {
    name: "Non-inferiority with Bonferroni (3 variants)",
    baseline: 0.1,
    relativeEffectSize: 0.08,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "bonferroni",
    expectedSampleSize: 22075,
  },
  {
    name: "Non-inferiority with Sidak (4 variants)",
    baseline: 0.15,
    relativeEffectSize: 0.12,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "sidak",
    expectedSampleSize: 6909,
  },
  {
    name: "Non-inferiority with buffer",
    baseline: 0.08,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 20,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 17064,
  },
  // Start of tests generated from TrialSize::TwoSampleProportion.Equivalence on 2025-06-21
  {
    name: "Basic equivalence",
    baseline: 0.1,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "equivalence",
    correctionMethod: "none",
    expectedSampleSize: 15415,
  },
  {
    name: "Tight equivalence",
    baseline: 0.2,
    relativeEffectSize: 0.05,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "equivalence",
    correctionMethod: "none",
    expectedSampleSize: 27404,
  },
  {
    name: "Loose equivalence",
    baseline: 0.15,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.85,
    variantCount: 2,
    buffer: 0,
    testType: "equivalence",
    correctionMethod: "none",
    expectedSampleSize: 4792,
  },
  {
    name: "High power equivalence",
    baseline: 0.3,
    relativeEffectSize: 0.08,
    alpha: 0.05,
    power: 0.95,
    variantCount: 2,
    buffer: 0,
    testType: "equivalence",
    correctionMethod: "none",
    expectedSampleSize: 9475,
  },
  {
    name: "Conservative equivalence",
    baseline: 0.05,
    relativeEffectSize: 0.06,
    alpha: 0.025,
    power: 0.9,
    variantCount: 2,
    buffer: 0,
    testType: "equivalence",
    correctionMethod: "none",
    expectedSampleSize: 137166,
  },
  {
    name: "Strict alpha equivalence",
    baseline: 0.12,
    relativeEffectSize: 0.1,
    alpha: 0.01,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "equivalence",
    correctionMethod: "none",
    expectedSampleSize: 19092,
  },
  {
    name: "E-commerce equivalence",
    baseline: 0.03,
    relativeEffectSize: 0.2,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "equivalence",
    correctionMethod: "none",
    expectedSampleSize: 13845,
  },
  {
    name: "Email equivalence",
    baseline: 0.25,
    relativeEffectSize: 0.08,
    alpha: 0.05,
    power: 0.9,
    variantCount: 2,
    buffer: 0,
    testType: "equivalence",
    correctionMethod: "none",
    expectedSampleSize: 10146,
  },
  {
    name: "Click rate equivalence",
    baseline: 0.08,
    relativeEffectSize: 0.12,
    alpha: 0.025,
    power: 0.85,
    variantCount: 2,
    buffer: 0,
    testType: "equivalence",
    correctionMethod: "none",
    expectedSampleSize: 18458,
  },
  {
    name: "Purchase equivalence",
    baseline: 0.45,
    relativeEffectSize: 0.04,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "equivalence",
    correctionMethod: "none",
    expectedSampleSize: 13084,
  },
  // End of tests generated from TrialSize::TwoSampleProportion.Equivalence on 2025-06-21
];

// Test that MDE -> SampleSize -> MDE returns the original MDE.
const symmetryTestCases = [
  {
    name: "Symmetry: Standard Two-Sided",
    baseline: 5.0,
    mde: 10.0,
    isRelative: true,
    testType: "two-sided",
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
  },
  {
    name: "Symmetry: Absolute MDE",
    baseline: 2.5,
    mde: 0.5,
    isRelative: false,
    testType: "two-sided",
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
  },
  {
    name: "Symmetry: High Power One-Sided",
    baseline: 20.0,
    mde: 5.0,
    isRelative: true,
    testType: "one-sided",
    alpha: 0.05,
    power: 0.95,
    variantCount: 2,
  },
  {
    name: "Symmetry: Equivalence, Bonferroni",
    baseline: 10.0,
    mde: 1.5,
    isRelative: false,
    testType: "equivalence",
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    correction: "bonferroni",
  },
  {
    name: "Symmetry: Non-Inferiority, Sidak",
    baseline: 15.0,
    mde: 4.0,
    isRelative: true,
    testType: "non-inferiority",
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    correction: "sidak",
  },
  {
    name: "Symmetry: One-Sided, Absolute MDE",
    baseline: 8.0,
    mde: 0.75,
    isRelative: false,
    testType: "one-sided",
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
  },
  {
    name: "Symmetry: Equivalence, Relative MDE (2 Variants)",
    baseline: 40.0,
    mde: 2.0,
    isRelative: true,
    testType: "equivalence",
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
  },
  {
    name: "Symmetry: Non-Inferiority, Absolute Margin",
    baseline: 50.0,
    mde: 0.5,
    isRelative: false,
    testType: "non-inferiority",
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    correction: "bonferroni",
  },
  {
    name: "Symmetry: Multi-Variant, No Correction",
    baseline: 12.0,
    mde: 8.0,
    isRelative: true,
    testType: "two-sided",
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    correction: "none",
  },
  {
    name: "Symmetry: Edge Case - Very Low Baseline",
    baseline: 0.2,
    mde: 50.0,
    isRelative: true,
    testType: "two-sided",
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
  },
  {
    name: "Symmetry: Edge Case - Very High Baseline",
    baseline: 95.0,
    mde: 1.0,
    isRelative: true,
    testType: "one-sided",
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
  },
];

async function runDirectTest(testCase) {
  debugLog(`Running test: ${testCase.name}`, "header");

  try {
    const calculatedSampleSize = calculateSampleSize(
      testCase.baseline,
      testCase.relativeEffectSize,
      testCase.alpha,
      testCase.power,
      testCase.variantCount,
      testCase.buffer || 0,
      testCase.testType || "two-sided",
      testCase.correctionMethod || "none"
    );

    debugLog(`  Calculated sample size: ${calculatedSampleSize}`);

    const difference = calculatedSampleSize - testCase.expectedSampleSize;
    const percentDiff = (
      (difference / testCase.expectedSampleSize) *
      100
    ).toFixed(3);

    debugLog(`  Difference: ${difference} (${percentDiff}%)`);

    if (calculatedSampleSize === testCase.expectedSampleSize) {
      debugLog(`Test passed`, "pass");
      passedTests++;
      return true;
    } else if (areClose(calculatedSampleSize, testCase.expectedSampleSize)) {
      debugLog(`Test passed: Results are within tolerance`, "pass");
      passedTests++;
      return true;
    } else {
      debugLog(`Test failed: Results exceed tolerance`, "fail");
      failedTests++;
      failedTestNames.push(testCase.name);
      return false;
    }
  } catch (error) {
    debugLog(`Test error: ${error.message}`, "fail");
    failedTests++;
    failedTestNames.push(`${testCase.name} (Error: ${error.message})`);
    return false;
  }
}

async function runSymmetryTest(testCase) {
  debugLog(`Test: ${testCase.name}`, "subheader");
  const originalGetParams = window.getCalculationParameters;
  window.getCalculationParameters = () => ({
    baseline: testCase.baseline,
    mde: testCase.mde,
    variantCount: testCase.variantCount,
    alpha: testCase.alpha,
    power: testCase.power,
    testType: testCase.testType,
    buffer: 0,
    isRelativeMode: testCase.isRelative,
    correctionMethod: testCase.correction || "none",
  });
  try {
    const mdeInfo = calculateMDE(
      testCase.baseline,
      testCase.mde,
      testCase.isRelative,
      testCase.testType
    );
    const preciseSampleSize = calculateSampleSize(
      mdeInfo.baselineRate,
      mdeInfo.relMDE,
      testCase.alpha,
      testCase.power,
      testCase.variantCount,
      0,
      testCase.testType,
      testCase.correction || "none"
    );
    const recoveredMde = calculateMDEFromSampleSize(
      preciseSampleSize,
      window.getCalculationParameters()
    );
    if (areClose(testCase.mde, recoveredMde)) {
      debugLog(
        `Test passed - Original MDE: ${testCase.mde.toFixed(
          2
        )}, Recovered: ${recoveredMde.toFixed(2)}`,
        "pass"
      );
      passedTests++;
    } else {
      debugLog(
        `Test failed - Original MDE: ${testCase.mde.toFixed(
          2
        )}, Recovered: ${recoveredMde.toFixed(2)}`,
        "fail"
      );
      failedTests++;
      failedTestNames.push(`${testCase.name}`);
    }
  } catch (error) {
    debugLog(`Test error: ${error.message}`, "fail");
    failedTests++;
    failedTestNames.push(`${testCase.name} (Error)`);
  } finally {
    window.getCalculationParameters = originalGetParams;
  }
}

async function runAllTests() {
  debugLog("Running tests…", "header");
  passedTests = 0;
  failedTests = 0;
  failedTestNames = [];
  for (const testCase of regressionTestCases) {
    await runDirectTest(testCase);
  }
  debugLog("Running symmetry (bi-directionality) tests...", "header");
  for (const testCase of symmetryTestCases) {
    await runSymmetryTest(testCase);
  }
  const totalTests = regressionTestCases.length + symmetryTestCases.length;
  debugLog(
    `${passedTests}/${totalTests} tests passed (${Math.round(
      (passedTests / totalTests) * 100
    )}%)`,
    "summary"
  );
  if (failedTests === 0) {
    debugLog("All tests passed! 🎉", "pass");
  } else {
    debugLog(`${failedTests} tests failed. Failed tests:`, "fail");
    failedTestNames.forEach((testName, index) => {
      debugLog(` ${index + 1}. ${testName}`, "fail");
    });
  }
}

function initTests() {
  if (window.location.search.includes("?test")) {
    if (!document.getElementById("debug-panel")) {
      document.body.appendChild(createDebugPanel());
    }
    runAllTests();
  }
}

initTests();
