let passedTests = 0;
let failedTests = 0;
let failedTestNames = [];

function areClose(a, b, tolerance = 0.01) {
  if (a === 0 && b === 0) return true;
  const relError = Math.abs((a - b) / Math.max(Math.abs(a), Math.abs(b)));
  return relError <= tolerance;
}

function createDebugPanel() {
  const debugPanel = document.createElement("div");
  debugPanel.id = "debug-panel";
  debugPanel.style.cssText =
    "position: fixed; bottom: 10px; right: 10px; background: rgba(30,30,30,0.9); color: white; padding: 10px; width: 500px; max-height: 500px; overflow-y: auto; font-family: monospace; font-size: 12px; z-index: 9999; border-radius: 6px; box-shadow: 0 4px 8px rgba(0,0,0,0.3); transition: all 0.3s ease;";

  const header = document.createElement("div");
  header.style.cssText =
    "display: flex; justify-content: space-between; align-items: center; margin-bottom: 8px; padding-bottom: 8px; border-bottom: 1px solid rgba(255,255,255,0.2);";

  const title = document.createElement("h3");
  title.textContent = "🧪 Test results";
  title.style.cssText = "margin: 0; font-size: 14px; color: #fff;";

  const closeButton = document.createElement("button");
  closeButton.textContent = "×";
  closeButton.style.cssText =
    "background: none; border: none; color: #ccc; font-size: 18px; cursor: pointer; padding: 0 5px;";
  closeButton.onclick = function () {
    debugPanel.style.opacity = "0";
    setTimeout(() => {
      debugPanel.style.display = "none";
    }, 300);
  };

  header.appendChild(title);
  header.appendChild(closeButton);
  debugPanel.appendChild(header);

  const content = document.createElement("div");
  content.id = "debug-content";
  content.style.cssText = "overflow-y: auto; max-height: 320px;";
  debugPanel.appendChild(content);

  const controls = document.createElement("div");
  controls.style.cssText =
    "display: flex; justify-content: space-between; margin-top: 8px; padding-top: 8px; border-top: 1px solid rgba(255,255,255,0.2);";

  const clearButton = document.createElement("button");
  clearButton.textContent = "Clear";
  clearButton.style.cssText =
    "background: #555; border: none; color: white; padding: 4px 8px; border-radius: 3px; cursor: pointer; font-size: 11px;";
  clearButton.onclick = function () {
    document.getElementById("debug-content").innerHTML = "";
    passedTests = 0;
    failedTests = 0;
  };

  const runTestsButton = document.createElement("button");
  runTestsButton.textContent = "Run Tests Again";
  runTestsButton.style.cssText =
    "background: #4a90e2; border: none; color: white; padding: 4px 8px; border-radius: 3px; cursor: pointer; font-size: 11px;";
  runTestsButton.onclick = function () {
    document.getElementById("debug-content").innerHTML = "";
    passedTests = 0;
    failedTests = 0;
    runAllTests();
  };

  controls.appendChild(clearButton);
  controls.appendChild(runTestsButton);
  debugPanel.appendChild(controls);

  return debugPanel;
}

function debugLog(message, type = "info") {
  const content = document.getElementById("debug-content");
  if (!content) return;

  const p = document.createElement("div");
  p.style.cssText =
    "margin: 4px 0; padding: 3px 0; border-bottom: 1px solid rgba(255,255,255,0.1);";

  switch (type) {
    case "pass":
      p.style.color = "#4caf50";
      message = `✅ ${message}`;
      break;
    case "fail":
      p.style.color = "#f44336";
      message = `❌ ${message}`;
      break;
    case "header":
      p.style.fontWeight = "bold";
      p.style.color = "#ffeb3b";
      p.style.paddingTop = "6px";
      break;
    case "summary":
      p.style.fontWeight = "bold";
      p.style.marginTop = "8px";
      break;
    default:
      p.style.color = "#ffffff";
  }

  p.textContent = message;
  content.appendChild(p);
  console.log(message);

  requestAnimationFrame(() => {
    content.scrollTop = content.scrollHeight;
  });
}

// Test cases based on Python's output.
const testCases = [
  {
    name: "E-commerce (one-sided)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "one-sided",
    expectedSampleSize: 24601,
  },
  {
    name: "E-commerce (two-sided)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    testType: "two-sided",
    expectedSampleSize: 31231,
  },
  {
    name: "High CR (one-sided)",
    baseline: 0.5,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    testType: "one-sided",
    expectedSampleSize: 1231,
  },
  {
    name: "Low CR (one-sided)",
    baseline: 0.01,
    relativeEffectSize: 0.2,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    testType: "one-sided",
    expectedSampleSize: 33627,
  },
  {
    name: "Small effect (one-sided)",
    baseline: 0.05,
    relativeEffectSize: 0.05,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    testType: "one-sided",
    expectedSampleSize: 96195,
  },
  {
    name: "Three variants (one-sided; Šidák)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    testType: "one-sided",
    expectedSampleSize: 31110,
    correctionMethod: "sidak",
  },
  {
    name: "High power (one-sided)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.01,
    power: 0.9,
    variantCount: 2,
    testType: "one-sided",
    expectedSampleSize: 51795,
  },
  {
    name: "Very low CR (one-sided)",
    baseline: 0.001,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    testType: "one-sided",
    expectedSampleSize: 590140,
  },
  {
    name: "Ultra high confidence (one-sided)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.001,
    power: 0.8,
    variantCount: 2,
    testType: "one-sided",
    expectedSampleSize: 61514,
  },
  {
    name: "Many variants (one-sided; Šidák)",
    baseline: 0.1,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    testType: "one-sided",
    expectedSampleSize: 8063,
    correctionMethod: "sidak",
  },
  {
    name: "Typical e-commerce",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 31231,
  },
  {
    name: "High conversion rate",
    baseline: 0.5,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 1562,
  },
  {
    name: "Low conversion rate",
    baseline: 0.01,
    relativeEffectSize: 0.2,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 42691,
  },
  {
    name: "Small effect size",
    baseline: 0.05,
    relativeEffectSize: 0.05,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 122121,
  },
  {
    name: "Three variants (Šidák)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    expectedSampleSize: 37700,
    correctionMethod: "sidak",
  },
  {
    name: "High power",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.01,
    power: 0.9,
    variantCount: 2,
    expectedSampleSize: 59206,
  },
  {
    name: "Edge case: very low CR",
    baseline: 0.001,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 749194,
  },
  {
    name: "Very high CR",
    baseline: 0.75,
    relativeEffectSize: 0.08,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 745,
  },
  {
    name: "Modest CR",
    baseline: 0.25,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 2190,
  },
  {
    name: "Mobile app CR",
    baseline: 0.035,
    relativeEffectSize: 0.12,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 31787,
  },
  {
    name: "Super low CR",
    baseline: 0.0025,
    relativeEffectSize: 0.18,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 210662,
  },
  {
    name: "Four variants (Šidák)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    expectedSampleSize: 41497,
    correctionMethod: "sidak",
  },
  {
    name: "Five variants (Šidák)",
    baseline: 0.1,
    relativeEffectSize: 0.12,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    expectedSampleSize: 14612,
    correctionMethod: "sidak",
  },
  {
    name: "Very high power",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.01,
    power: 0.95,
    variantCount: 2,
    expectedSampleSize: 70883,
  },
  {
    name: "Conservative test",
    baseline: 0.15,
    relativeEffectSize: 0.08,
    alpha: 0.001,
    power: 0.9,
    variantCount: 2,
    expectedSampleSize: 38216,
  },
  {
    name: "Tiny effect",
    baseline: 0.1,
    relativeEffectSize: 0.03,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 159063,
  },
  {
    name: "Ultra low CR, large effect",
    baseline: 0.0005,
    relativeEffectSize: 0.25,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 564798,
  },
  {
    name: "Ultra high confidence",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.0001,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 89106,
  },
  {
    name: "Very low confidence",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.8,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 4771,
  },
  {
    name: "Microscopic CR",
    baseline: 0.0001,
    relativeEffectSize: 0.2,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 4316406,
  },
  {
    name: "Near perfect CR",
    baseline: 0.9999,
    relativeEffectSize: 0.0001,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 79282,
  },
  {
    name: "Near certain detection",
    baseline: 0.1,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.9999,
    variantCount: 2,
    expectedSampleSize: 60600,
  },
  {
    name: "Very low power",
    baseline: 0.1,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.1,
    variantCount: 2,
    expectedSampleSize: 865,
  },
  {
    name: "Minuscule effect",
    baseline: 0.5,
    relativeEffectSize: 0.001,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    expectedSampleSize: 15697752,
  },
  {
    name: "Many variants, low alpha (Šidák)",
    baseline: 0.01,
    relativeEffectSize: 0.1,
    alpha: 0.001,
    power: 0.99,
    variantCount: 10,
    expectedSampleSize: 796477,
    correctionMethod: "sidak",
  },
  {
    name: "Low CR, many variants (Šidák)",
    baseline: 0.001,
    relativeEffectSize: 0.05,
    alpha: 0.05,
    power: 0.8,
    variantCount: 8,
    expectedSampleSize: 10175229,
    correctionMethod: "sidak",
  },
  {
    name: "Realistic extreme",
    baseline: 0.0005,
    relativeEffectSize: 0.5,
    alpha: 0.1,
    power: 0.7,
    variantCount: 2,
    expectedSampleSize: 94053,
  },
  {
    name: "Buffer test (10%)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 10,
    testType: "two-sided",
    expectedSampleSize: 34354, // 31231 * 1.1
  },
  {
    name: "Buffer test (25%)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 25,
    testType: "two-sided",
    expectedSampleSize: 39039, // 31231 * 1.25
  },
  {
    name: "Buffer test (100%)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 100,
    testType: "two-sided",
    expectedSampleSize: 62462, // 31231 * 2
  },
  {
    name: "E-commerce (3 variants, none)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 31231,
  },
  {
    name: "E-commerce (3 variants, bonferroni)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 37821,
  },
  {
    name: "E-commerce (3 variants, sidak)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 37700,
  },
  {
    name: "E-commerce (5 variants, none)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 31231,
  },
  {
    name: "E-commerce (5 variants, bonferroni)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 44371,
  },
  {
    name: "E-commerce (5 variants, sidak)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 44190,
  },
  {
    name: "High traffic site (3 variants, none)",
    baseline: 0.1,
    relativeEffectSize: 0.08,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 22853,
  },
  {
    name: "High traffic site (3 variants, bonferroni)",
    baseline: 0.1,
    relativeEffectSize: 0.08,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 27674,
  },
  {
    name: "High traffic site (3 variants, sidak)",
    baseline: 0.1,
    relativeEffectSize: 0.08,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 27586,
  },
  {
    name: "High traffic site (5 variants, none)",
    baseline: 0.1,
    relativeEffectSize: 0.08,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 22853,
  },
  {
    name: "High traffic site (5 variants, bonferroni)",
    baseline: 0.1,
    relativeEffectSize: 0.08,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 32467,
  },
  {
    name: "High traffic site (5 variants, sidak)",
    baseline: 0.1,
    relativeEffectSize: 0.08,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 32335,
  },
  {
    name: "Low CR site (3 variants, none)",
    baseline: 0.01,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 74191,
  },
  {
    name: "Low CR site (3 variants, bonferroni)",
    baseline: 0.01,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 89845,
  },
  {
    name: "Low CR site (3 variants, sidak)",
    baseline: 0.01,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 89558,
  },
  {
    name: "Low CR site (5 variants, none)",
    baseline: 0.01,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 74191,
  },
  {
    name: "Low CR site (5 variants, bonferroni)",
    baseline: 0.01,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 105404,
  },
  {
    name: "Low CR site (5 variants, sidak)",
    baseline: 0.01,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 104976,
  },
  {
    name: "E-commerce checkout",
    baseline: 0.03,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 10,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 26610,
  },
  {
    name: "Email click-through",
    baseline: 0.12,
    relativeEffectSize: 0.08,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "one-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 14652,
  },
  {
    name: "SaaS sign-up",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.9,
    variantCount: 2,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 41810,
  },
  {
    name: "Micro-conversion (near zero)",
    baseline: 0.0001,
    relativeEffectSize: 0.5,
    alpha: 0.05,
    power: 0.85,
    variantCount: 2,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 897724,
  },
  {
    name: "High-penetration market (near 100%)",
    baseline: 0.98,
    relativeEffectSize: 0.01,
    alpha: 0.01,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 3612,
  },
  {
    name: "Tiny effect detection",
    baseline: 0.2,
    relativeEffectSize: 0.005,
    alpha: 0.05,
    power: 0.95,
    variantCount: 2,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 4166092,
  },
  {
    name: "Massive effect detection",
    baseline: 0.1,
    relativeEffectSize: 2.0,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "one-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 47,
  },
  {
    name: "Ultra-precise test",
    baseline: 0.5,
    relativeEffectSize: 0.1,
    alpha: 0.001,
    power: 0.99,
    variantCount: 2,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 6279,
  },
  {
    name: "Copy variants (5 options)",
    baseline: 0.08,
    relativeEffectSize: 0.12,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 18776,
  },
  {
    name: "Pricing matrix (16 variants)",
    baseline: 0.15,
    relativeEffectSize: 0.2,
    alpha: 0.05,
    power: 0.8,
    variantCount: 16,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 4344,
  },
  {
    name: "Multi-arm no correction",
    baseline: 0.04,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 17940,
  },
  {
    name: "Multi-arm Bonferroni",
    baseline: 0.04,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 23929,
  },
  {
    name: "Multi-arm Sidak",
    baseline: 0.04,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 23837,
  },
  {
    name: "Standard buffer (20%)",
    baseline: 0.1,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 20,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 17699, // 14749 * 1.2
  },
  {
    name: "Large buffer (50%)",
    baseline: 0.1,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 50,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 22124, // 14749 * 1.5
  },
  {
    name: "Huge buffer (100%)",
    baseline: 0.1,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 100,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 29498, // 14749 * 2.0
  },
  {
    name: "Mobile app purchase",
    baseline: 0.005,
    relativeEffectSize: 0.3,
    alpha: 0.05,
    power: 0.9,
    variantCount: 2,
    buffer: 15,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 61400, // 53391 * 1.15
  },
  {
    name: "Blog subscription (early stage)",
    baseline: 0.01,
    relativeEffectSize: 0.4,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "one-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 9160,
  },
  {
    name: "Premium upsell",
    baseline: 0.002,
    relativeEffectSize: 0.25,
    alpha: 0.1,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 111033,
  },
  {
    name: "Freemium activation",
    baseline: 0.35,
    relativeEffectSize: 0.06,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 25,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 12418, // 9934 * 1.25
  },
  {
    name: "Equal variance edge case",
    baseline: 0.5,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 1562,
    baseSampleSize: 1562,
  },
  {
    name: "Low-power exploratory",
    baseline: 0.2,
    relativeEffectSize: 0.2,
    alpha: 0.05,
    power: 0.6,
    variantCount: 2,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 1049,
    baseSampleSize: 1049,
  },
  {
    name: "High alpha exploration",
    baseline: 0.15,
    relativeEffectSize: 0.15,
    alpha: 0.2,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 2407,
    baseSampleSize: 2407,
  },
  {
    name: "One-sided high stakes",
    baseline: 0.01,
    relativeEffectSize: 0.5,
    alpha: 0.005,
    power: 0.98,
    variantCount: 2,
    buffer: 0,
    testType: "one-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 21155,
    baseSampleSize: 21155,
  },
  {
    name: "Very small alpha (bonferroni)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.001,
    power: 0.8,
    variantCount: 10,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 88143,
  },
  {
    name: "Very small alpha (sidak)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.001,
    power: 0.8,
    variantCount: 10,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 88139,
  },
  {
    name: "Many variants (bonferroni)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 15,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 56115,
  },
  {
    name: "Many variants (sidak)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 15,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 55894,
  },
  {
    name: "Many variants (none)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 15,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 31231,
  },
  {
    name: "Variant count = 2 (bonferroni)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 31231,
  },
  {
    name: "Variant count = 3 (bonferroni)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 37821,
  },
  {
    name: "Buffer + correction",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 20,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 53245,
  },
  {
    name: "One-sided + correction",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "one-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 37640,
  },
  {
    name: "Extreme low CR + correction",
    baseline: 0.001,
    relativeEffectSize: 0.2,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 612631,
  },
  {
    name: "Tiny MDE + correction",
    baseline: 0.05,
    relativeEffectSize: 0.01,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 4240183,
  },
  {
    name: "High variant count (8, none)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 8,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 31231,
  },
  {
    name: "High variant count (8, bonferroni)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 8,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 49631,
  },
  {
    name: "High variant count (8, sidak)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 8,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 49426,
  },
  {
    name: "High variant count (12, none)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 12,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 31231,
  },
  {
    name: "High variant count (12, bonferroni)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 12,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 53863,
  },
  {
    name: "High variant count (12, sidak)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 12,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 53646,
  },
  {
    name: "High variant count (20, none)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 20,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 31231,
  },
  {
    name: "High variant count (20, bonferroni)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 20,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 58961,
  },
  {
    name: "High variant count (20, sidak)",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 20,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 58736,
  },

  // Extreme alpha values
  {
    name: "Alpha=0.0001",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.0001,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 89106,
  },
  {
    name: "Alpha=0.0001 w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.0001,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 101733,
  },
  {
    name: "Alpha=0.0001 w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.0001,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 101733,
  },
  {
    name: "Alpha=0.001",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.001,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 67941,
  },
  {
    name: "Alpha=0.001 w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.001,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 80714,
  },
  {
    name: "Alpha=0.001 w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.001,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 80711,
  },
  {
    name: "Alpha=0.1",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.1,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 24601,
  },
  {
    name: "Alpha=0.1 w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.1,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 37821,
  },
  {
    name: "Alpha=0.1 w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.1,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 37451,
  },
  {
    name: "Alpha=0.2",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.2,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 17937,
  },
  {
    name: "Alpha=0.2 w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.2,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 31231,
  },
  {
    name: "Alpha=0.2 w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.2,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 30451,
  },

  // Test type interaction
  {
    name: "one-sided",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 0,
    testType: "one-sided",
    correctionMethod: "none",
    expectedSampleSize: 24601,
  },
  {
    name: "one-sided w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 0,
    testType: "one-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 35091,
  },
  {
    name: "one-sided w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 0,
    testType: "one-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 34929,
  },
  {
    name: "two-sided",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 31231,
  },
  {
    name: "two-sided w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 41657,
  },
  {
    name: "two-sided w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 41497,
  },

  // Extreme conversion rates
  {
    name: "CR=0.0001",
    baseline: 0.0001,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 16480913,
  },
  {
    name: "CR=0.0001 w/ Bonferroni",
    baseline: 0.0001,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 19958477,
  },
  {
    name: "CR=0.0001 w/ Šidák",
    baseline: 0.0001,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 19894748,
  },
  {
    name: "CR=0.001",
    baseline: 0.001,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 1646531,
  },
  {
    name: "CR=0.001 w/ Bonferroni",
    baseline: 0.001,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 1993958,
  },
  {
    name: "CR=0.001 w/ Šidák",
    baseline: 0.001,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 1987591,
  },
  {
    name: "CR=0.999",
    baseline: 0.999,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 1,
  },
  {
    name: "CR=0.999 w/ Bonferroni",
    baseline: 0.999,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 1,
  },
  {
    name: "CR=0.999 w/ Šidák",
    baseline: 0.999,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 1,
  },
  {
    name: "CR=0.9999",
    baseline: 0.9999,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 1,
  },
  {
    name: "CR=0.9999 w/ Bonferroni",
    baseline: 0.9999,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 1,
  },
  {
    name: "CR=0.9999 w/ Šidák",
    baseline: 0.9999,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 1,
  },

  // Extreme MDE values
  {
    name: "MDE=0.001",
    baseline: 0.05,
    relativeEffectSize: 0.001,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 298398702,
  },
  {
    name: "MDE=0.001 w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.001,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 361362478,
  },
  {
    name: "MDE=0.001 w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.001,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 360208624,
  },
  {
    name: "MDE=0.01",
    baseline: 0.05,
    relativeEffectSize: 0.01,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 2996695,
  },
  {
    name: "MDE=0.01 w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.01,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 3629014,
  },
  {
    name: "MDE=0.01 w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.01,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 3617426,
  },
  {
    name: "MDE=0.5",
    baseline: 0.05,
    relativeEffectSize: 0.5,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 1468,
  },
  {
    name: "MDE=0.5 w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.5,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 1778,
  },
  {
    name: "MDE=0.5 w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.5,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 1772,
  },
  {
    name: "MDE=0.8",
    baseline: 0.05,
    relativeEffectSize: 0.8,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 635,
  },
  {
    name: "MDE=0.8 w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.8,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 769,
  },
  {
    name: "MDE=0.8 w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.8,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 767,
  },

  // Buffer interaction
  {
    name: "Buffer=10%",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 10,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 34354,
  },
  {
    name: "Buffer=10% w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 10,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 45823,
  },
  {
    name: "Buffer=10% w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 10,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 45646,
  },
  {
    name: "Buffer=50%",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 50,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 46847,
  },
  {
    name: "Buffer=50% w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 50,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 62485,
  },
  {
    name: "Buffer=50% w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 50,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 62245,
  },
  {
    name: "Buffer=100%",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 100,
    testType: "two-sided",
    correctionMethod: "none",
    expectedSampleSize: 62462,
  },
  {
    name: "Buffer=100% w/ Bonferroni",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 100,
    testType: "two-sided",
    correctionMethod: "bonferroni",
    expectedSampleSize: 83314,
  },
  {
    name: "Buffer=100% w/ Šidák",
    baseline: 0.05,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 100,
    testType: "two-sided",
    correctionMethod: "sidak",
    expectedSampleSize: 82993,
  },
  {
    name: "Basic non-inferiority",
    baseline: 0.1,
    relativeEffectSize: -0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 11129,
    status: "success",
  },
  {
    name: "Conservative non-inferiority",
    baseline: 0.05,
    relativeEffectSize: -0.05,
    alpha: 0.025,
    power: 0.9,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 159713,
    status: "success",
  },
  {
    name: "High power non-inferiority",
    baseline: 0.2,
    relativeEffectSize: -0.15,
    alpha: 0.05,
    power: 0.95,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 3848,
    status: "success",
  },
  {
    name: "Low baseline non-inferiority",
    baseline: 0.02,
    relativeEffectSize: -0.2,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 15148,
    status: "success",
  },
  {
    name: "High baseline non-inferiority",
    baseline: 0.3,
    relativeEffectSize: -0.08,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 4509,
    status: "success",
  },
  {
    name: "Non-inferiority with Bonferroni (3 variants)",
    baseline: 0.1,
    relativeEffectSize: -0.08,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "bonferroni",
    expectedSampleSize: 22075,
    status: "success",
  },
  {
    name: "Non-inferiority with Sidak (4 variants)",
    baseline: 0.15,
    relativeEffectSize: -0.12,
    alpha: 0.05,
    power: 0.8,
    variantCount: 4,
    buffer: 0,
    testType: "non-inferiority",
    correctionMethod: "sidak",
    expectedSampleSize: 6909,
    status: "success",
  },
  {
    name: "Non-inferiority with buffer",
    baseline: 0.08,
    relativeEffectSize: -0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 20,
    testType: "non-inferiority",
    correctionMethod: "none",
    expectedSampleSize: 17064,
    status: "success",
  },
{
    name: "Basic equivalence",
    baseline: 0.1,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "equivalence",
    correctionMethod: "none",
    expectedSampleSize: 15415,
    status: "success",
  },
  {
    name: "Tight equivalence margin",
    baseline: 0.15,
    relativeEffectSize: 0.05,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "equivalence",
    correctionMethod: "none",
    expectedSampleSize: 38823,
    status: "success",
  },
  {
    name: "Low baseline equivalence",
    baseline: 0.02,
    relativeEffectSize: 0.25,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "equivalence",
    correctionMethod: "none",
    expectedSampleSize: 13429,
    status: "success",
  },
  {
    name: "High baseline equivalence",
    baseline: 0.4,
    relativeEffectSize: 0.08,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "equivalence",
    correctionMethod: "none",
    expectedSampleSize: 4015,
    status: "success",
  },
  {
    name: "High power equivalence",
    baseline: 0.12,
    relativeEffectSize: 0.1,
    alpha: 0.025,
    power: 0.9,
    variantCount: 2,
    buffer: 0,
    testType: "equivalence",
    correctionMethod: "none",
    expectedSampleSize: 19059,
    status: "success",
  },
  {
    name: "Equivalence with Bonferroni (3 variants)",
    baseline: 0.1,
    relativeEffectSize: 0.1,
    alpha: 0.05,
    power: 0.8,
    variantCount: 3,
    buffer: 0,
    testType: "equivalence",
    correctionMethod: "bonferroni",
    expectedSampleSize: 18914,
    status: "success",
  },
  {
    name: "Equivalence with Sidak (5 variants)",
    baseline: 0.08,
    relativeEffectSize: 0.12,
    alpha: 0.05,
    power: 0.8,
    variantCount: 5,
    buffer: 0,
    testType: "equivalence",
    correctionMethod: "sidak",
    expectedSampleSize: 19741,
    status: "success",
  },
  {
    name: "Equivalence with buffer",
    baseline: 0.06,
    relativeEffectSize: 0.15,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 25,
    testType: "equivalence",
    correctionMethod: "none",
    expectedSampleSize: 14908,
    status: "success",
  },
  {
    name: "Very low baseline equivalence",
    baseline: 0.001,
    relativeEffectSize: 0.5,
    alpha: 0.05,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "equivalence",
    correctionMethod: "none",
    expectedSampleSize: 68443,
    status: "success",
  },
  {
    name: "High alpha equivalence",
    baseline: 0.1,
    relativeEffectSize: 0.1,
    alpha: 0.1,
    power: 0.8,
    variantCount: 2,
    buffer: 0,
    testType: "equivalence",
    correctionMethod: "none",
    expectedSampleSize: 11826,
    status: "success",
  },
];

async function runDirectTest(testCase) {
  debugLog(`Running test: ${testCase.name}`, "header");

  try {
    const calculatedSampleSize = calculateSampleSize(
      testCase.baseline,
      testCase.relativeEffectSize,
      testCase.alpha,
      testCase.power,
      testCase.variantCount,
      testCase.buffer || 0,
      testCase.testType || "two-sided",
      testCase.correctionMethod || "none"
    );

    debugLog(`  Calculated sample size: ${calculatedSampleSize}`);

    const difference = calculatedSampleSize - testCase.expectedSampleSize;
    const percentDiff = (
      (difference / testCase.expectedSampleSize) *
      100
    ).toFixed(3);

    debugLog(`  Difference: ${difference} (${percentDiff}%)`);

    if (calculatedSampleSize === testCase.expectedSampleSize) {
      debugLog(`Test passed`, "pass");
      passedTests++;
      return true;
    } else if (areClose(calculatedSampleSize, testCase.expectedSampleSize)) {
      debugLog(`Test passed: Results are within tolerance`, "pass");
      passedTests++;
      return true;
    } else {
      debugLog(`Test failed: Results exceed tolerance`, "fail");
      failedTests++;
      failedTestNames.push(testCase.name);
      return false;
    }
  } catch (error) {
    debugLog(`Test error: ${error.message}`, "fail");
    failedTests++;
    failedTestNames.push(`${testCase.name} (Error: ${error.message})`);
    return false;
  }
}

async function runAllTests() {
  debugLog("Running tests…", "header");
  passedTests = 0;
  failedTests = 0;
  failedTestNames = [];
  for (const testCase of testCases) {
    await runDirectTest(testCase);
  }
  const totalTests = testCases.length;
  debugLog(
    `${passedTests}/${totalTests} tests passed (${Math.round(
      (passedTests / totalTests) * 100
    )}%)`,
    "summary"
  );
  if (failedTests === 0) {
    debugLog("All tests passed! 🎉", "pass");
  } else {
    debugLog(`${failedTests} tests failed. Failed tests:`, "fail");
    failedTestNames.forEach((testName, index) => {
      debugLog(` ${index + 1}. ${testName}`, "fail");
    });
  }
}

function initTests() {
  if (window.location.search.includes("?test")) {
    if (!document.getElementById("debug-panel")) {
      document.body.appendChild(createDebugPanel());
    }
    runAllTests();
  }
}

initTests();
